import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "mahdi",
      email: "mahdi.da128@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "mohammad",
      email: "mdal@gmail.com",
      password: bcrypt.hashSync("12345"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: "1",
      name: "Samsung Galaxy S22 Ultra",
      slug: "galaxy-s22-ultra",
      category: "phones",
      image: "/images/s22ultra.jpg",
      price: 1000,
      countInStock: 4,
      brand: "Samsung",
      rating: 4.9,
      description: "Android Overall Flagship Phone in 2022",
      numReviews: 24,
    },
    {
      // _id: "2",
      name: "Pixel 7 Pro",
      slug: "pixel-7-pro",
      category: "phones",
      image: "/images/pixel7pro.jpg",
      price: 850,
      countInStock: 8,
      brand: "Pixel",
      rating: 3.8,
      description: "Google Flagship Phone in 2022",
      numReviews: 41,
    },
    {
      //  _id: "3",
      name: "Xiaomi 13 Pro",
      slug: "xiaomi-13-pro",
      category: "phones",
      image: "/images/xiaomi13pro.jpg",
      price: 950,
      countInStock: 0,
      brand: "Xiaomi",
      rating: 4,
      description: "Chinese Flagship Phone in 2022",
      numReviews: 22,
    },
    {
      //  _id: "4",
      name: "Iphone 14 ProMax",
      slug: "iphone-14-pro-max",
      category: "phones",
      image: "/images/iphone14promax.jpg",
      price: 1300,
      countInStock: 22,
      brand: "Apple",
      rating: 5,
      description: "Apple Flagship Phone in 2022",
      numReviews: 13,
    },
  ],
};
export default data;
